name: GitHub CI

on:
  push:
    branches: [master]
    paths-ignore:
      - "*.md"
      - "src/*"
      - "LICENSE"
      - ".gitignore"
  pull_request:
    branches: [master]
    paths-ignore:
      - "*.md"
      - "src/*"
      - "LICENSE"
      - ".gitignore"
  workflow_dispatch:

jobs:
  test-on-ubuntu:
    env:
      PANDOC_VERSION: "2.11.1.1"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: pandoc.deb
          key: ${{ runner.os }}--${{ env.PANDOC_VERSION }}
      - run: |
          if ! [ -f pandoc.deb ]; then
            printf '***** On %s. Downloading pandoc.deb\n' "$PWD"
            sudo apt-get update
            sudo apt-get install -y curl
            curl -fsSL -o pandoc.deb "https://github.com/jgm/pandoc/releases/download/$PANDOC_VERSION/pandoc-$PANDOC_VERSION-1-amd64.deb"
          fi
          sudo apt-get install -y ./pandoc.deb
      - run: |
          printf '***** On %s.\n' "$PWD"
          make check
