name: Run tests

on:
  push:
    branches: [master]
    paths-ignore:
      - "*.md"
      - "src/*"
      - "LICENSE"
      - ".gitignore"
  pull_request:
    branches: [master]
    paths-ignore:
      - "*.md"
      - "src/*"
      - "LICENSE"
      - ".gitignore"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/cache@v2
        with:
          path: pandoc.deb
          key: ${{ runner.os }}-${{ hashFiles('pandoc.deb') }}
      - run: |
          sudo apt-get update
          if ! [ -f pandoc.deb ]; then
            sudo apt-get install -y curl
            curl -fsSL -o pandoc.deb 'https://github.com/jgm/pandoc/releases/download/2.11.1.1/pandoc-2.11.1.1-1-amd64.deb'
          fi
          sudo apt-get install -y ./pandoc.deb
      - uses: actions/checkout@v2
      - run: |
          make check
